// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 // @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 1. Keep the autogenerated sidebar for existing content
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },

    // 2. Add custom section for AI + Playwright guides
    {
      type: 'category',
      label: 'AI + Playwright',
      collapsed: false,
      items: [
        'ai-playwright/overview'         // maps to docs/ai-playwright/overview.m,

      ],
    },
  ],
};

export default sidebars;